#pragma once
#include <string>

#define RPL_WELCOME(nickname) (":NeTwerkers 001 " + nickname + " :Welcome to the Internet Relay Network, " + nickname + "!\r\n")
#define RPL_YOURHOST(nickname) (":NeTwerkers 002 " + nickname + " :Your host is NeTwerkers, running version v0.1\r\n")
#define RPL_CREATED(nickname, date) (":NeTwerkers 003 " + nickname + " This server was created " + date + "\r\n")
#define RPL_MYINFO(nickname) (":NeTwerkers 004 " + nickname + " NetTwerkers v0.1 itkol\r\n")
#define RPL_WHOISUSER(client, nickname, username, host, real_name) (":NeTwerkers 311 " + client + " " + nickname + " " + username + " " + host + " * :" + real_name + "\r\n")
#define RPL_WHOISSERVER(client, nickname, server, server_info) (":NeTwerkers 312 " + client + " " + nickname + " " + server + " :" + server_info+ "\r\n")
#define RPL_WHOISCHANNELS(client, nickname, channels) (":NeTwerkers 319 " + client + " " + nickname + " :" + channels + "\r\n")
#define RPL_WHOISIDLE(client, nickname, seconds, signon_time) (":NeTwerkers 317 " + client + " " + nickname + " " + seconds + " " + signon_time + " :seconds idle, signon time"+ "\r\n")
#define RPL_ENDOFWHOIS(client, nickname) (":NeTwerkers 318 " + client + " " + nickname + " :End of WHOIS list"+ "\r\n")
#define RPL_NOTOPIC(client, channel) (":NeTwerkers 331 " + client + " " + channel + " :No topic is set\r\n")
#define RPL_TOPIC(channel, nickname, topic) (":NeTwerkers 332 " + nickname + " " + channel + " :" + topic + "\r\n")
#define RPL_INVITING(client, nickname, channel) (":NeTwerkers 341 " + client + " " + nickname + " " + channel + "\r\n")
#define RPL_INVITED(channel, nickname, prefix) (":" + prefix + " INVITE " + nickname + " " + channel + "\r\n")
#define RPL_NAMREPLY(client, channel, nicknames) (":NeTwerkers 353 " + client + " = " + channel + " :" + nicknames+ "\r\n")   
#define RPL_ENDOFNAMES(client, channel) (":NeTwerkers 366 " + client + " " + channel + " :End of NAMES list"+ "\r\n")
#define RPL_JOIN(prefix, channel ) (":" + prefix + " JOIN " + channel + "\r\n")
#define RPL_PART(prefix, channel, message) (":" + prefix + " PART " + channel + " :" + message + "\r\n")
#define RPL_PRIVMSG(prefix, target, message) (":" + prefix + " PRIVMSG " + target + " :" + message + "\r\n")
#define RPL_NEWNICK(prefix, nickname) (":" + prefix + " NICK " + nickname + "\r\n")

#define ERR_NOSUCHCHANNEL(nickname, channel) (":NeTwerkers 403 " + nickname + " " +  channel + " :No such channel" + "\r\n")
#define ERR_TOOMANYTARGETS(nickname, target) (":NeTwerkers 407 " + nickname + " " +  target + " :Duplicate recipients. No message delivered" + "\r\n")
#define ERR_NORECIPIENT(nickname) (":NeTwerkers 411 " + nickname + " :No recipient given (PRIVMSG)\r\n")
#define ERR_BADCHANNELKEY(client, channel) (":NeTwerkers 475 " + client + " " + channel + " :Cannot join channel (+k) \r\n")
#define ERR_NOSUCHNICK(client, nickname) (":NeTwerkers 401 " + client + " " + nickname + " :No such nick/channel\r\n")
#define ERR_UNKNOWNCOMMAND( command) (":NeTwerkers 421 " + command + " :Unknown command\r\n")
#define ERR_NONICKNAMEGIVEN(client) (":NeTwerkers 431 " + client + " :No nickname given\r\n")
#define ERR_ERRONEUSNICKNAME(nickname) (":NeTwerkers 432 NICK " + nickname + " :Erroneous nickname\r\n")
#define ERR_NICKNAMEINUSE(nickname) (":NeTwerkers 433 NICK " + nickname + " :Nickname is already in use\r\n")
#define ERR_USERNOTINCHANNEL(nickname, channel) (":NeTwerkers 441 " + channel + " " + nickname + " :They aren't on that channel\r\n")
#define ERR_NOTONCHANNEL(client, channel) (":NeTwerkers 442 " + client + " " + channel + " :You're not on that channel\r\n")
#define ERR_USERONCHANNEL(nickname, channel) (":NeTwerkers 443 " + nickname + " " + channel + " :is already on channel\r\n")
#define ERR_NOTREGISTERED(command) (":NeTwerkers 451 " + command + " :You have not registered\r\n")
#define ERR_NEEDMOREPARAMS(nickname, command) (":NeTwerkers 461 " + nickname + " " + command + " :Not enough parameters\r\n")
#define ERR_ALREADYREGISTRED(command) (":NeTwerkers 462 " + command + " :You may not reregister\r\n")
#define ERR_PASSWDMISMATCH() (":NeTwerkers 464 PASS :Password incorrect\r\n")
#define ERR_CHANNELISFULL(client, channel) (":NeTwerkers 471 " + client + " " + channel + " :Cannot join channel (+l)\r\n")
#define ERR_UNKNOWNMODE(client, mode) (":NeTwerkers 472 " + client + " " + mode + " :is unknown mode char to me\r\n")
#define ERR_INVITEONLYCHAN(client, channel) (":NeTwerkers 473 " + client + " " + channel + " :Cannot join channel (+i)\r\n")
#define ERR_NOCHANMODES(client, channel) (":NeTwerkers 477 " + client + " " + channel + " :Channel doesn't support modes\r\n")
#define ERR_CHANOPRIVSNEEDED(client, channel) (":NeTwerkers 482 " + client + " " + channel + " :You're not channel operator\r\n")
#define ERR_INVALIDMODEPARAM(client, target, modeChar, parameter, description) (":NeTwerkers 696 " + client + " " + target + " " + modeChar + " " + parameter + " :" + description + "\r\n")
#define ERR_INVALIDKEY(client, target) (":NeTwerkers 525 " + client + " " + target + " :Key is not well-formed\r\n")

void	rplSend(int fd, std::string rpl);
